site_name: Documentação
theme:
  name: flatly
nav:
    - 'index.md'
    - 'Dicas':
        - 'add_alias.md'
        - 'git_push.md'
        - 'mkdocs.md'
        - 'platformio.md'
        - 'server_python_HTTP.md'
        - 'settings_vscode.md'
        - 'Usando_MarkDown.md'
        - 'verificando_processos_maquina_linux.md'
        - 'vi.md'
    - 'Configurações e instalações':
        - 'esp32_ttgo_lcd.md'
        - 'Instalação_vuejs_e _vuetify.md'
        - 'installing_mysql_data-base.md'
        - 'installing_postgresql.md'
        - 'install_psycopg2.md'
        - 'xrandr_linux.md'
palette:
    primary: 'teal'
    accent: 'blue'
font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
logo:
    icon: 'important_devices'
language: 'pt'
repo_name: 'm4rlonr'
repo_url: 'https://github.com/m4rlonr'
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
extra:
  theme_inverse: false
